spring:
  application:
    name: users-service-virunga
#  Database config
  datasource:
    url: jdbc:postgresql://localhost:5433/users-virunga-DB
    username: ${USERNAME}
    password: password
    driver-class-name: org.postgresql.Driver
#    Security config
  security:
    user:
      name: admin
      password: admin1234

# JPA config
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-request-size: 10MB
      enabled: true
      max-file-size: 10MB

server:
  port: 8081
  servlet:
    context-path: /api/v1

# For debugging
logging:
  level:
    org.springframework.security.authentication: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security: DEBUG

