spring:
  application:
    name: virunga-service
  datasource:
    url: jdbc:postgresql://localhost:5432/virungaDB
    username: postgres
    password: 09200The
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
