spring:
  application:
    name: product-service-virunga
  datasource:
    url: ${DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  # ðŸ”‘ Keycloak Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8790/realms/virunga-auth
      client:
        registration:
          keycloak:
            client-id: virunga-client-auth
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: http://localhost:8790/realms/virunga-auth
            token-uri: http://localhost:8790/realms/virunga-auth/protocol/openid-connect/token
            authorization-uri: http://localhost:8790/realms/virunga-auth/protocol/openid-connect/auth
            user-info-uri: http://localhost:8790/realms/virunga-auth/protocol/openid-connect/userinfo


server:
  port: 8080
  servlet:
    context-path: /api/v1/


# For debugging
logging:
  level:
    org.springframework.security.authentication: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security: DEBUG
